### PR TITLE
Upgrade to SBT 0.13.16 and make it an Autoplugin 

### PR DESCRIPTION
**Pull request by alonsodomin**
This PR upgrades the plugin to latest version of SBT, removing all deprecated syntax by their counterparts post SBT 0.13.14+ and makes the plugin an AutoPlugin, effectively setting it ready for the upcoming SBT 1.0.0 release.

`.sbt` build files for all of the SBT scripted tests are now replacing the old `Build.scala`, which will be removed in SBT 1.0.0.

Everything compiles and passes tests. No changes in the logic inside the plugin have been done, with the exception of moving the keys out of the plugin class, the rest is just a translation from the old syntax to the new one.

### CODE REVIEW

**Comment by alonsodomin** [comment]
Any chance of merging this into master at any point?

**Comment by alonsodomin** [comment]
@pvlugter Updated the SBT version to 0.13.16 which gives the ability of cross compiling SBT plugins. Any chance of reviewing this and potentially merge it? It would be great to get this plugin working with SBT 1.0.0

**Comment by pvlugter** [comment]
@alonsodomin, are you interested in being an official contributor for this project, so that you have admin rights and can publish releases?

**Comment by alonsodomin** [comment]
@pvlugter I do have an interest on keeping this plugin alive since at work we rely on it to instrument some services so I would like to see it supporting sbt 1.0.0.

Not too sure if I'm the best person to keep evolving the plugin (i.e.: adding new features to it) though but could do my best in addressing some common maintenance tasks...

**Comment by pvlugter** [comment]
@alonsodomin, great, I've sent an invite for a github team. The plugin is published to bintray sbt-plugin-releases. Let's get you set up for publishing too.

**Comment by pvlugter** [comment]
Added cross-building for sbt 1.0. Also made some other updates: added sbt-release, sbt settings have been renamed to have `aspectj` prefix, switched to `com.lightbend.sbt` org.

**Comment by pvlugter** [comment]
Released `0.11.0`.

**Pull request merged**
